name: ncov_outbreaker
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - augur=12.0.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - biopython==1.76
  - bioconductor-Biostrings
  - bioconductor-ggtree
  - click==8.0.3
  - fasttree=2.1.10
  - iqtree=2.1.2
  - mafft=7.480
  - numpy=1.20.3
  - pandas=1.2.4
  - pandoc=>2.1.3
  - pango=1.48.5
  - pip=21.1.2
  - pytest=6.2.4
  - python=3.8.10
  - raxml=8.2.12
  - r-argparse
  - r-base=>3.6.3
  - r-dplyr=1.0.7
  - r-dt
  - r-markdown
  - r-essentials
  - r-traminer
  - scipy=1.6.3
  - snakemake-minimal=6.4.1
  - snp-dists=0.8.2
  - snp-sites=2.5.1
  - vcftools=0.1.16
  - pip:
    - Bio
    - git+git://github.com/matt-sd-watson/FASTAfurious
