name: ncov_spora
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - augur=12.0.0
  - biopython==1.76
  - bioconductor-Biostrings
  - bioconductor-ggtree
  - click==8.0.3
  - fasttree=2.1.10
  - iqtree=2.1.2
  - mafft=7.480
  - numpy==1.24.3
  - pandas=1.2.4
  - pandoc=>2.1.3
  - pango=1.48.5
  - pip=21.1.2
  - pulp==2.7.0
  - pytest=6.2.4
  - python=3.8.10
  - raxml=8.2.12
  - r-argparse
  - r-base=>3.6.3
  - r-dplyr>=1.0.9
  - r-dt
  - r-heatmaply
  - r-markdown
  - r-essentials
  - r-plotly
  - r-traminer
  - scipy=1.6.3
  - snakemake
  - snp-dists=0.8.2
  - snp-sites=2.5.1
  - vcftools=0.1.16
  - pip:
    - Bio
    - git+https://github.com/matt-sd-watson/FASTAfurious.git
    - git+https://github.com/aineniamh/snipit.git
    - pypandoc>=1.8
