# This is a basic workflow to help you get started with Actions

name: outbreaker_CI

# Controls when the workflow will run
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environments/environment.yml
          activate-environment: ncov_outbreaker
          channels: conda-forge,bioconda,defaults
      - name: Install outbreaker
        shell: bash -l {0}
        run: pip install -e .
      - name: Check outbreaker version
        shell: bash -l {0}
        run: outbreaker -v
