
name: outbreaker_CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environments/environment.yml
          activate-environment: ncov_outbreaker
          channels: conda-forge,bioconda,defaults,r
      - name: Install outbreaker
        shell: bash -l {0}
        run: pip install -e .
      - name: Check outbreaker version
        shell: bash -l {0}
        run: outbreaker -v
      - name: Run outbreaker test via CLI
        shell: bash -l {0}
        run: outbreaker -f data/tests/focal_seqs.fa -b data/tests/background_seqs.fa -r data/reference/ncov_reference.gb -o outbreaker_test -p test --snps-only --report --rename --names-csv data/tests/names.csv
      - name: Run outbreaker test via config
        shell: bash -l {0}
        run: outbreaker -c data/test_config.yaml
      - name: Run pytest for outbreaker
        shell: bash -l {0}
        run: pytest tests/
